name: Sync Secrets

on:
  workflow_dispatch:

jobs:
  sync-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Sync Secrets
        uses: jpoehnelt/secrets-sync-action@v1.9.0
        with:
          SECRETS: |
            ^NPM_AUTH_TOKEN$
          REPOSITORIES: |
            ^link108/sync-secrets-to$
          DRY_RUN: true
          GITHUB_TOKEN: ${{ secrets.SYNC_TOKEN }}
